/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DocumentId = IDL.Nat;
export const TagId = IDL.Nat;
export const Document = IDL.Record({
  'id' : DocumentId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'tagIds' : IDL.Vec(TagId),
  'updatedAt' : IDL.Int,
});
export const Tag = IDL.Record({
  'id' : TagId,
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const BacklinkRef = IDL.Record({
  'id' : DocumentId,
  'title' : IDL.Text,
});
export const GraphEdge = IDL.Record({
  'source' : DocumentId,
  'target' : DocumentId,
});
export const GraphNode = IDL.Record({ 'id' : DocumentId, 'title' : IDL.Text });
export const GraphData = IDL.Record({
  'edges' : IDL.Vec(GraphEdge),
  'nodes' : IDL.Vec(GraphNode),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DocumentVersion = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'savedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDocument' : IDL.Func([IDL.Text], [Document], []),
  'createTag' : IDL.Func([IDL.Text, IDL.Text], [Tag], []),
  'deleteDocument' : IDL.Func([DocumentId], [], []),
  'deleteTag' : IDL.Func([TagId], [], []),
  'getAllTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
  'getBacklinks' : IDL.Func([DocumentId], [IDL.Vec(BacklinkRef)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocument' : IDL.Func([DocumentId], [IDL.Opt(Document)], ['query']),
  'getDocumentByTitle' : IDL.Func([IDL.Text], [IDL.Opt(Document)], ['query']),
  'getDocuments' : IDL.Func(
      [IDL.Text, IDL.Vec(TagId), IDL.Text],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'getGraphData' : IDL.Func([], [GraphData], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getVersions' : IDL.Func([DocumentId], [IDL.Vec(DocumentVersion)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'restoreVersion' : IDL.Func([DocumentId, IDL.Nat], [Document], []),
  'saveVersion' : IDL.Func([DocumentId], [], []),
  'setProfile' : IDL.Func([IDL.Text], [], []),
  'updateDocument' : IDL.Func(
      [DocumentId, IDL.Text, IDL.Text, IDL.Vec(TagId)],
      [Document],
      [],
    ),
  'updateTag' : IDL.Func([TagId, IDL.Text, IDL.Text], [Tag], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DocumentId = IDL.Nat;
  const TagId = IDL.Nat;
  const Document = IDL.Record({
    'id' : DocumentId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'tagIds' : IDL.Vec(TagId),
    'updatedAt' : IDL.Int,
  });
  const Tag = IDL.Record({
    'id' : TagId,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const BacklinkRef = IDL.Record({ 'id' : DocumentId, 'title' : IDL.Text });
  const GraphEdge = IDL.Record({
    'source' : DocumentId,
    'target' : DocumentId,
  });
  const GraphNode = IDL.Record({ 'id' : DocumentId, 'title' : IDL.Text });
  const GraphData = IDL.Record({
    'edges' : IDL.Vec(GraphEdge),
    'nodes' : IDL.Vec(GraphNode),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DocumentVersion = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'savedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDocument' : IDL.Func([IDL.Text], [Document], []),
    'createTag' : IDL.Func([IDL.Text, IDL.Text], [Tag], []),
    'deleteDocument' : IDL.Func([DocumentId], [], []),
    'deleteTag' : IDL.Func([TagId], [], []),
    'getAllTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
    'getBacklinks' : IDL.Func([DocumentId], [IDL.Vec(BacklinkRef)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocument' : IDL.Func([DocumentId], [IDL.Opt(Document)], ['query']),
    'getDocumentByTitle' : IDL.Func([IDL.Text], [IDL.Opt(Document)], ['query']),
    'getDocuments' : IDL.Func(
        [IDL.Text, IDL.Vec(TagId), IDL.Text],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'getGraphData' : IDL.Func([], [GraphData], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getVersions' : IDL.Func(
        [DocumentId],
        [IDL.Vec(DocumentVersion)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'restoreVersion' : IDL.Func([DocumentId, IDL.Nat], [Document], []),
    'saveVersion' : IDL.Func([DocumentId], [], []),
    'setProfile' : IDL.Func([IDL.Text], [], []),
    'updateDocument' : IDL.Func(
        [DocumentId, IDL.Text, IDL.Text, IDL.Vec(TagId)],
        [Document],
        [],
      ),
    'updateTag' : IDL.Func([TagId, IDL.Text, IDL.Text], [Tag], []),
  });
};

export const init = ({ IDL }) => { return []; };