/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BacklinkRef { 'id' : DocumentId, 'title' : string }
export interface Document {
  'id' : DocumentId,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'tagIds' : Array<TagId>,
  'updatedAt' : bigint,
}
export type DocumentId = bigint;
export interface DocumentVersion {
  'title' : string,
  'content' : string,
  'savedAt' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface GraphData {
  'edges' : Array<GraphEdge>,
  'nodes' : Array<GraphNode>,
}
export interface GraphEdge { 'source' : DocumentId, 'target' : DocumentId }
export interface GraphNode { 'id' : DocumentId, 'title' : string }
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface Tag { 'id' : TagId, 'name' : string, 'color' : string }
export type TagId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDocument' : ActorMethod<[string], Document>,
  'createTag' : ActorMethod<[string, string], Tag>,
  'deleteDocument' : ActorMethod<[DocumentId], undefined>,
  'deleteTag' : ActorMethod<[TagId], undefined>,
  'getAllTags' : ActorMethod<[], Array<Tag>>,
  'getBacklinks' : ActorMethod<[DocumentId], Array<BacklinkRef>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[DocumentId], [] | [Document]>,
  'getDocumentByTitle' : ActorMethod<[string], [] | [Document]>,
  'getDocuments' : ActorMethod<[string, Array<TagId>, string], Array<Document>>,
  'getGraphData' : ActorMethod<[], GraphData>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getVersions' : ActorMethod<[DocumentId], Array<DocumentVersion>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'restoreVersion' : ActorMethod<[DocumentId, bigint], Document>,
  'saveVersion' : ActorMethod<[DocumentId], undefined>,
  'setProfile' : ActorMethod<[string], undefined>,
  'updateDocument' : ActorMethod<
    [DocumentId, string, string, Array<TagId>],
    Document
  >,
  'updateTag' : ActorMethod<[TagId, string, string], Tag>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];